/**
 * api/daily-theme.js — Vercel Cron (запускается в 04:00 UTC каждый день)
 * Обновляет тему игры: генерирует новый config.js и коммитит в репозиторий.
 *
 * Расписание в vercel.json: "0 4 * * *"
 */

// Список возможных тем — ротация по дням
const THEMES = [
  {
    id: 'cyberpunk', name: 'Cyberpunk',
    colors: { background:'#0a0a1a', primary:'#00fff5', secondary:'#ff00a8', accent:'#ffe600', platform:'#1a1a3e', ball:'#ffe600' },
    font: '"Orbitron", monospace', physics: { gravity: 1.2, ballRestitution: 0.35 },
  },
  {
    id: 'noir', name: 'Нуар',
    colors: { background:'#0d0d0d', primary:'#e8d5a3', secondary:'#8b0000', accent:'#c9a96e', platform:'#2a2a2a', ball:'#f0e6d3' },
    font: '"Special Elite", serif', physics: { gravity: 1.1, ballRestitution: 0.25 },
  },
  {
    id: 'space', name: 'Космос',
    colors: { background:'#020212', primary:'#7b68ee', secondary:'#ff6b35', accent:'#ffd700', platform:'#0f0f3a', ball:'#7b68ee' },
    font: '"Exo 2", sans-serif', physics: { gravity: 0.8, ballRestitution: 0.5 },
  },
  {
    id: 'neon', name: 'Неон',
    colors: { background:'#000000', primary:'#39ff14', secondary:'#ff073a', accent:'#ff6600', platform:'#0a1a0a', ball:'#39ff14' },
    font: '"Bungee", cursive', physics: { gravity: 1.3, ballRestitution: 0.4 },
  },
  {
    id: 'steampunk', name: 'Стимпанк',
    colors: { background:'#1a0f00', primary:'#cd7f32', secondary:'#8b4513', accent:'#ffa500', platform:'#2d1f0a', ball:'#daa520' },
    font: '"Cinzel", serif', physics: { gravity: 1.4, ballRestitution: 0.2 },
  },
  {
    id: 'ocean', name: 'Океан',
    colors: { background:'#000f1a', primary:'#00bfff', secondary:'#006994', accent:'#40e0d0', platform:'#001a2e', ball:'#00bfff' },
    font: '"Raleway", sans-serif', physics: { gravity: 0.9, ballRestitution: 0.45 },
  },
  {
    id: 'forest', name: 'Лес',
    colors: { background:'#0a150a', primary:'#228b22', secondary:'#8b4513', accent:'#adff2f', platform:'#1a2a1a', ball:'#adff2f' },
    font: '"Josefin Sans", sans-serif', physics: { gravity: 1.15, ballRestitution: 0.3 },
  },
];

export default async function handler(req, res) {
  // Проверяем крон-авторизацию Vercel
  if (req.headers['authorization'] !== `Bearer ${process.env.CRON_SECRET}`) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  // Определяем тему дня
  const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0)) / 86400000);
  const theme = THEMES[dayOfYear % THEMES.length];
  const day   = dayOfYear;

  // Генерируем новый config.js
  const configContent = generateConfig(theme, day);

  // Коммитим в GitHub через API
  const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
  const REPO         = process.env.GITHUB_REPO; // 'username/bolt-drop'

  if (GITHUB_TOKEN && REPO) {
    try {
      // Получаем текущий SHA файла
      const fileRes = await fetch(`https://api.github.com/repos/${REPO}/contents/config.js`, {
        headers: { Authorization: `token ${GITHUB_TOKEN}`, Accept: 'application/vnd.github.v3+json' },
      });
      const fileData = await fileRes.json();
      const sha = fileData.sha;

      // Обновляем файл
      await fetch(`https://api.github.com/repos/${REPO}/contents/config.js`, {
        method: 'PUT',
        headers: {
          Authorization:  `token ${GITHUB_TOKEN}`,
          'Content-Type': 'application/json',
          Accept:         'application/vnd.github.v3+json',
        },
        body: JSON.stringify({
          message: `🎨 Daily theme: ${theme.name} (Day ${day})`,
          content: Buffer.from(configContent).toString('base64'),
          sha,
        }),
      });

      console.log(`[DailyTheme] ✅ Updated to "${theme.name}" (Day ${day})`);
    } catch (err) {
      console.error('[DailyTheme] GitHub API error:', err);
    }
  }

  return res.status(200).json({ theme: theme.id, day, message: 'Theme updated' });
}

function generateConfig(theme, day) {
  const c = theme.colors;
  return `/**
 * config.js — AUTO-GENERATED by daily-theme cron
 * Theme: ${theme.name} | Day: ${day} | Date: ${new Date().toISOString().split('T')[0]}
 */

export const THEME = {
  name: '${theme.name}',
  id:   '${theme.id}',
  day:  ${day},
  colors: {
    background:   '${c.background}',
    primary:      '${c.primary}',
    secondary:    '${c.secondary}',
    accent:       '${c.accent}',
    platform:     '${c.platform}',
    platformEdge: '${c.primary}',
    bolt:         '${c.secondary}',
    boltGlow:     '${c.secondary}88',
    ball:         '${c.ball}',
    ballGlow:     '${c.accent}',
    goal:         '${c.primary}',
    goalGlow:     '${c.primary}',
    danger:       '#ff2222',
    text:         '#e0e0ff',
    ui:           '#0f0f2e',
    uiBorder:     '${c.primary}',
  },
  assets: {
    background:   'assets/${theme.id}/bg.png',
    platform:     'assets/${theme.id}/plank.png',
    bolt:         'assets/${theme.id}/bolt.png',
    ball:         'assets/${theme.id}/ball.png',
    goal:         'assets/${theme.id}/goal.png',
    particleBolt: 'assets/${theme.id}/particle_bolt.png',
    particleWin:  'assets/${theme.id}/particle_win.png',
    bgMusic:      'assets/${theme.id}/ambient.ogg',
    sfxBolt:      'assets/${theme.id}/sfx_bolt.ogg',
    sfxWin:       'assets/${theme.id}/sfx_win.ogg',
    sfxLose:      'assets/${theme.id}/sfx_lose.ogg',
  },
  css: {
    '--color-bg':           '${c.background}',
    '--color-primary':      '${c.primary}',
    '--color-secondary':    '${c.secondary}',
    '--color-accent':       '${c.accent}',
    '--color-text':         '#e0e0ff',
    '--color-ui-bg':        '#0f0f2e',
    '--color-ui-border':    '${c.primary}',
    '--font-display':       '${theme.font}',
    '--font-body':          '${theme.font}',
    '--glow-primary':       '0 0 12px ${c.primary}, 0 0 24px ${c.primary}',
    '--glow-secondary':     '0 0 12px ${c.secondary}, 0 0 24px ${c.secondary}',
    '--glow-ball':          '0 0 16px ${c.ball}, 0 0 32px ${c.accent}',
  },
  physics: {
    gravity:              ${theme.physics.gravity},
    ballRestitution:      ${theme.physics.ballRestitution},
    ballFriction:         0.08,
    platformFriction:     0.4,
    platformRestitution:  0.1,
    airResistance:        0.01,
    boltRadius:           14,
    ballRadius:           18,
  },
  visual: {
    platformH:      16,
    boltRemoveAnim: 'sparks',
    winParticles:   'stars',
    screenShake:    true,
    glowEffects:    true,
  },
};

export const SHOP_PRODUCTS = {
  hints_pack:      { id:'hints_pack',      title:'💡 Пакет подсказок ×5',      description:'5 подсказок', price:50,  currency:'XTR', payload:'hints_pack_5',      quantity:5 },
  no_ads:          { id:'no_ads',          title:'🚫 Отключение рекламы',       description:'Навсегда',    price:100, currency:'XTR', payload:'no_ads_permanent',  duration:-1 },
  infinite_lives:  { id:'infinite_lives',  title:'❤️ Бесконечные жизни 24ч',  description:'24 часа',     price:150, currency:'XTR', payload:'infinite_lives_24h', durationHours:24 },
};

export const GAME_CONFIG = {
  width: 450, height: 800, maxLives: 3, livesRegenMin: 30, adsEvery: 3,
};
`;
}
